---
title: "week 2"
output: html_notebook
---
## Lattice Plotting
```{r}
library(lattice)
xyplot(Ozone ~ Wind, data = airquality)

```
```{r}
airquality<-transform(airquality,Month = factor(Month))
xyplot(Ozone ~ Wind|Month, data = airquality,layout =c(5,1))


```

## LAtice panel function

```{r}
set.seed(10)
x <- rnorm(100)
f <- rep(0:1,each = 50)
y <-x +f - f*x+rnorm(100,sd=.5)
f <- factor(f, labels = c("Group 1","Group 2"))
xyplot(y~x|f,layout =c(2,1))

```
```{r}
xyplot(y~x|f,panel = function(x,y,...){
  panel.xyplot(x,y,...)
  panel.abline(h=median(y),lty=2)
  panel.lmline(x,y,col=2)
})

```


## ggplot

```{r}
library(ggplot2)

qplot(displ, hwy, data=mpg,col =drv)
```
```{r}
qplot(displ, hwy, data=mpg,geom = c("point","smooth"))

```
### histogram
```{r}
qplot(hwy,data=mpg,fill=drv)
```

### facets
```{r}
qplot(displ, hwy, data=mpg,facets = .~drv)

qplot(hwy,data=mpg,facets =drv~.,binwidth =2 )

```

## ggplot

```{r}
g <- ggplot(mpg,aes(displ,hwy)) + geom_point()
print(g)
```
```{r}
ggplot(mpg,aes(displ,hwy)) + geom_point() + geom_smooth()
```
```{r}
ggplot(mpg,aes(displ,hwy)) + geom_point() + geom_smooth(method ="lm")

```
```{r}
ggplot(mpg,aes(displ,hwy)) + geom_point() + facet_grid( drv ~.) +geom_smooth(method ="lm")

```


### Aesthetics  
```{r}

ggplot(mpg,aes(displ,hwy)) + geom_point(color = "steelblue",size = 2, alpha =2)


ggplot(mpg,aes(displ,hwy)) + geom_point(aes(color = drv),size = 2, alpha =1/2)

```

### labelling aamd customisinggs smooth CHANGING THEME
```{r}
ggplot(mpg,aes(displ,hwy)) + geom_point(aes(color = drv),size = 2, alpha =1/2) +labs(title=" MAIN TITLE HEREE", x= "X Label") + geom_smooth(size=1.5,linetype =2, method = "lm",se =FALSE) +
  theme_bw(base_family = "Times")
``` 

##Axis limits
```{r}
testdata <- data.frame(x =1:100 , y = rnorm(100))
testdata[50,2] <- 100
#plot(testdata$x ,testdata$y,type ="l", ylim = c(-3,3))

g <- ggplot(testdata,aes(x=x,y=y))
g+geom_line() + ylim(-3,3)
# here the extereme point is not plotted

g + geom_line() +coord_cartesian(ylim = c(-3,3))

```

## Final plt
```{r}
g <- ggplot(mpg,aes(displ,hwy))
g + geom_point(alpha=1/3) + facet_wrap(drv ~ year,nrow =2, ncol=3) + geom_smooth(method = "lm",se=FALSE , col= "steelblue") + theme_bw(base_family = "Avenir",base_size = 10) + labs(title = "MAIN TITKE") +labs(x= "X Label",y ="y label") 

```

