---
title: "Week 1"
output: html_notebook
---
## Base plot
```{r}
#library(datasets)
data(cars)
with(cars,plot(speed,dist))
```

## LAttice plot
```{r}
library(lattice)
state <-data.frame(state.x77,Region=state.region) 
xyplot(Life.Exp ~ Population | Region ,data=state, layout=c(4,1))
```

## ggplot2
```{r}
library(ggplot2)
data(mpg)
qplot(displ,hwy,data=mpg)
```

## Simple base graphs 
```{r}
#Histogram
par(bg="red")
hist(airquality$Ozone)

#Scatterplot
with(airquality,plot(Wind,Ozone,pch = 6))

#Boxplot
airquality <-transform(airquality,Month =factor(Month))
boxplot(Ozone~ Month,airquality,xlab = "MOnth",ylab = "Ozone (ppb)",lty=3        ,lwd=1.2)
```


##Baseplot with annatations
```{r}
with(airquality,plot(Wind,Ozone))
title(main = "MAIN TITLE")

```
```{r}
with(airquality,plot(Wind,Ozone,main = "MAIN TITLE"))
with(subset(airquality,Month ==5), points(Wind,Ozone,col="blue"))
with(subset(airquality,Month !=5), points(Wind,Ozone,col="red"))
legend("topright",pch=1,col = c("blue","red"),legend=c("May","other months"))

```

## add regression Line
```{r}
with(airquality,plot(Wind,Ozone,main = "MAIN TITLE",pch=20))
model <- lm(Ozone ~ Wind,airquality)
abline(model,lwd=2)
```

## Multiple base plot
```{r}
par(mfrow=c(1,2))
with(airquality,{
  plot(Wind,Ozone,main = "OZONe-WIND")
  plot(Solar.R, Ozone,main = "Ozone Solar Radiation")
})

```

```{r}
par(mfrow = c(1,3),mar = c(4,4,2,1),oma =c(0,0,2,0))
with(airquality,{
  plot(Wind,Ozone,main = "OZONe-WIND")
  plot(Solar.R, Ozone,main = "Ozone Solar Radiation")
  plot(Temp,Ozone, maim = "OZone and Temperature")
  mtext("Ozone and weather in NWEYORK",outer=TRUE)
})
```


## Demonstaration
```{r}
x <- rnorm(100)
hist(x)

y<- rnorm(100)
plot(x,y)

par(mar =c(4,4,2,2))
plot(x,y)

```

```{r}
plot(x,y,pch=20, xlab = "X Label",ylab =" y Label")
title("Scatterplot")
text(-2,1,"text")
legend("topleft", legend = "DATA",pch=1)

fit <- lm(y~x)
abline(fit , lwd=2,col="blue", lty=2)
```

```{r}
z <- rpois(100,2)
par(mfrow=c(2,1),mar=c(2,2,1,1))
plot(x,y)
  plot(x,z)
```

```{r}
x <- rnorm(100)
y<- x+ rnorm(100)
g <- gl(2,50,labels = c("M","F"))
plot(x,y,type="n")
points(x[g=="M"],y[g == "M"],col="red",pch=3)
points(x[g=="F"],y[g == "F"],col="blue",pch=4)

```


## Creating plot in PDF

```{r}
pdf(file = "testplot.pdf")
with(faithful,plot(eruptions,waiting))
title(main = "Old faithful geyserdata")
dev.off ()
```

## Copying
```{r}
with(faithful,plot(eruptions,waiting))
title(main = "Old faithful geyserdata")
dev.copy(png,file="testpng.png")
dev.off()
```

